package com.yc.shoesMall.dao;

import com.yc.shoesMall.bean.Imgs;
import com.yc.shoesMall.bean.ImgsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImgsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    long countByExample(ImgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int deleteByExample(ImgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int insert(Imgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int insertSelective(Imgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    List<Imgs> selectByExample(ImgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    Imgs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") Imgs record, @Param("example") ImgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int updateByExample(@Param("record") Imgs record, @Param("example") ImgsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int updateByPrimaryKeySelective(Imgs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table imgs
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int updateByPrimaryKey(Imgs record);
}