package com.yc.shoesMall.dao;

import com.yc.shoesMall.bean.Orders;
import com.yc.shoesMall.bean.OrdersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    long countByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    int deleteByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    int insertSelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    List<Orders> selectByExample(OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    Orders selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    int updateByExampleSelective(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    int updateByExample(@Param("record") Orders record, @Param("example") OrdersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    int updateByPrimaryKeySelective(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    int updateByPrimaryKey(Orders record);
    
    List<Orders> selectOrdersByPrimaryKey(Integer id);

}