
package com.yc.shoesMall.dao;

import com.yc.shoesMall.bean.Product;
import com.yc.shoesMall.bean.ProductSize;
import com.yc.shoesMall.bean.ProductSizeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductSizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_size
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    long countByExample(ProductSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_size
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int deleteByExample(ProductSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_size
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_size
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int insert(ProductSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_size
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int insertSelective(ProductSize record);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_size
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    List<ProductSize> selectByExample(ProductSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_size
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    ProductSize selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_size
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProductSize record, @Param("example") ProductSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_size
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int updateByExample(@Param("record") ProductSize record, @Param("example") ProductSizeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_size
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int updateByPrimaryKeySelective(ProductSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_size
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    int updateByPrimaryKey(ProductSize record);
}