package com.yc.shoesMall.bean;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.pid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.type_name
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.pid
     *
     * @return the value of category.pid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.pid
     *
     * @param pid the value for category.pid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.type_name
     *
     * @return the value of category.type_name
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.type_name
     *
     * @param typeName the value for category.type_name
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }
}