package com.yc.shoesMall.bean;

public class Imgs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.pid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.img_path
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column imgs.type
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.id
     *
     * @return the value of imgs.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.id
     *
     * @param id the value for imgs.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.pid
     *
     * @return the value of imgs.pid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.pid
     *
     * @param pid the value for imgs.pid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.img_path
     *
     * @return the value of imgs.img_path
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.img_path
     *
     * @param imgPath the value for imgs.img_path
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column imgs.type
     *
     * @return the value of imgs.type
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column imgs.type
     *
     * @param type the value for imgs.type
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}