
package com.yc.shoesMall.bean;

import java.math.BigDecimal;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.oid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.pid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.number
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_detail.price
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.id
     *
     * @return the value of order_detail.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.id
     *
     * @param id the value for order_detail.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.oid
     *
     * @return the value of order_detail.oid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.oid
     *
     * @param oid the value for order_detail.oid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.pid
     *
     * @return the value of order_detail.pid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.pid
     *
     * @param pid the value for order_detail.pid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.number
     *
     * @return the value of order_detail.number
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.number
     *
     * @param number the value for order_detail.number
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_detail.price
     *
     * @return the value of order_detail.price
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_detail.price
     *
     * @param price the value for order_detail.price
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}