package com.yc.shoesMall.bean;

import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_num
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.uid
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.count_price
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    private Long countPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.finish_time
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.address_id
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_method
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    private String payMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_size
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
     */
    private String orderSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_count
     *
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
     */
    private Integer orderCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_image
     *
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
     */
    private String orderImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.name
     *
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_num
     *
     * @return the value of orders.order_num
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_num
     *
     * @param orderNum the value for orders.order_num
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.uid
     *
     * @return the value of orders.uid
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.uid
     *
     * @param uid the value for orders.uid
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.count_price
     *
     * @return the value of orders.count_price
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public Long getCountPrice() {
        return countPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.count_price
     *
     * @param countPrice the value for orders.count_price
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public void setCountPrice(Long countPrice) {
        this.countPrice = countPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.finish_time
     *
     * @return the value of orders.finish_time
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.finish_time
     *
     * @param finishTime the value for orders.finish_time
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.address_id
     *
     * @return the value of orders.address_id
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.address_id
     *
     * @param addressId the value for orders.address_id
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_method
     *
     * @return the value of orders.pay_method
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public String getPayMethod() {
        return payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_method
     *
     * @param payMethod the value for orders.pay_method
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
=======
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
>>>>>>> refs/heads/syw
     */
    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod == null ? null : payMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_size
     *
     * @return the value of orders.order_size
     *
<<<<<<< HEAD
     * @mbg.generated Thu Sep 05 10:15:04 CST 2019
     */
 
    public String getOrderSize() {
        return orderSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_size
     *
     * @param orderSize the value for orders.order_size
     *
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
     */
    public void setOrderSize(String orderSize) {
        this.orderSize = orderSize == null ? null : orderSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_count
     *
     * @return the value of orders.order_count
     *
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
     */
    public Integer getOrderCount() {
        return orderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_count
     *
     * @param orderCount the value for orders.order_count
     *
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
     */
    public void setOrderCount(Integer orderCount) {
        this.orderCount = orderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_image
     *
     * @return the value of orders.order_image
     *
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
     */
    public String getOrderImage() {
        return orderImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_image
     *
     * @param orderImage the value for orders.order_image
     *
     * @mbg.generated Wed Sep 04 15:55:26 CST 2019
     */
    public void setOrderImage(String orderImage) {
        this.orderImage = orderImage == null ? null : orderImage.trim();
    }
}