
package com.yc.shoesMall.bean;

public class ProductBrand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_brand.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_brand.brand_name
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private String brandName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_brand.id
     *
     * @return the value of product_brand.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_brand.id
     *
     * @param id the value for product_brand.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_brand.brand_name
     *
     * @return the value of product_brand.brand_name
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_brand.brand_name
     *
     * @param brandName the value for product_brand.brand_name
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }
}