
package com.yc.shoesMall.bean;

import java.util.Date;

public class Wishlist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.uid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.pid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.create_time
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.id
     *
     * @return the value of wishlist.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.id
     *
     * @param id the value for wishlist.id
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.uid
     *
     * @return the value of wishlist.uid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.uid
     *
     * @param uid the value for wishlist.uid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.pid
     *
     * @return the value of wishlist.pid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.pid
     *
     * @param pid the value for wishlist.pid
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.create_time
     *
     * @return the value of wishlist.create_time
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.create_time
     *
     * @param createTime the value for wishlist.create_time
     *
     * @mbg.generated Mon Aug 26 14:20:54 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}